### ISSUE TITLE
Hello, can you provide a demo in which "WS2812FX-idf" works properly in idf?

### ISSUE THREAD

**Issue by songdehuai** [mriksman/WS2812FX-idf#1]
Hello, can you provide a demo in which "WS2812FX-idf" works properly in idf?

This will be very useful to me, thank you very much!

**Comment by mriksman** [comment]
It'd take me days to remember how to use it (and GitHub!). 
Check out this [repo of mine](https://github.com/mriksman/esp32_homekit_animations). It uses NeoPixelBus directly (which is well documented on their page).
It was intended for an ESP32 module with HomeKit emulation, so you can use it with Apple HomeKit. A TV Service allows you to turn on and off animations, and you can select an animation by changing the 'input source'. 
If you don't use HomeKit, the code should get you going at least.

**Comment by songdehuai** [comment]
Thank you very much！
